name: Update OpenAPI Sync Config
description: Updates `.github/workflows/openapi-sync.yml` based on renamed or deleted OpenAPI files in a PR.

author: Fern

inputs:
  token:
    description: GitHub token for authentication
    required: true


runs:
  using: node20
  main: dist/index.js
